"""
SQLAlchemy ORM models for RelocateIQ.
Each class here will map 1-to-1 to an entity in Figure 3 of the design doc:
  User, CommuteScenario, Workplace, PreferenceProfile, Zone,
  Recommendation, CommuteAnalysis, LifestyleAnalysis, HousingListing.

Also defines the ScenarioStatus enum used to track a scenario's lifecycle
(Figure 5 state machine).
"""
import enum
import uuid
from datetime import datetime
from typing import Optional

from sqlalchemy import (
    String, Integer, Float, Boolean, DateTime, ForeignKey, Text,
    Enum as SQLEnum,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.db.database import Base

def _uuid() -> str:
    """Generate a UUID4 as a string. Used as the default for primary keys."""
    return str(uuid.uuid4())

class ScenarioStatus(str, enum.Enum):
    """Lifecycle states for a CommuteScenario(see Figure 5 in the design doc)."""
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    ANALYZING = "ANALYZING"
    RANKED = "RANKED"
    EXPLAINED = "EXPLAINED"
    FAILED = "FAILED"
    SAVED = "SAVED"

#now to implement the actual modes
class User(Base):
    """This is a registered user of RelocateIQ. It can own 0 or more CommuteScenerios"""
    __tablename__="users"
    user_id: Mapped[str]=mapped_column(String,primary_key=True, default=_uuid)
    name: Mapped[str]=mapped_column(String, nullable=False)
    email:Mapped[str]=mapped_column(String,nullable=False, unique=True,index=True)
    
    #Since one user can have or or many scenerios.  The reverse side is CommuteScenerio.user
    scenarios: Mapped[list["CommuteScenario"]] = relationship(
        back_populates="user",
        cascade="all, delete-orphan",
    )
#Thisi is the CommunteScenario class which will serve as the central entity for one neighborhood search
class CommuteScenario(Base):
    """
    This is a single neighborhood search performed by a user.
    Each of these scenarios will be anchored to a single workplace, governed 
    by one PreferenceProfile, and produces several Recommendations as it moves throguh the
    lifecycle states we defined in ScenarioStatus
    """
    __tablename__="commute_scenarios"
    scenario_id:Mapped[str]=mapped_column(String, primary_key=True, default=_uuid)
    user_id: Mapped[str]=mapped_column(ForeignKey("users.user_id"), nullable=False, index=True)
    search_radius_miles: Mapped[float]=mapped_column(Float, nullable=False)
    created_at: Mapped[datetime]=mapped_column(DateTime, default=datetime.utcnow, nullable=False)
    status: Mapped[ScenarioStatus]=mapped_column(
        SQLEnum(ScenarioStatus,name="scenario_status"),
        default=ScenarioStatus.DRAFT,
        nullable=False
    )

    #reverse side of the User.scenarios
    user:Mapped["User"]=relationship(back_populates="scenarios")

    #Each one of the scenario has exactly one workplace and one preference profile
    workplace: Mapped["Workplace"] = relationship(
        back_populates="scenario",
        uselist=False,
        cascade="all, delete-orphan",
    )
    #Also only has one preference profile
    preference_profile: Mapped["PreferenceProfile"] = relationship(
        back_populates="scenario",
        uselist=False,
        cascade="all, delete-orphan",
    )
    #One scenario produces many recommendations (one per candidate zone).
    #order_by returns them already sorted by rank (1, 2, 3...) when accessed.
    recommendations: Mapped[list["Recommendation"]] = relationship(
        back_populates="scenario",
        cascade="all, delete-orphan",
        order_by="Recommendation.rank",
    )
#The workplace class
#The target offcie location for the scenario
class Workplace(Base):
    """
    A geocoded workplace address. One per CommuteScenario.
    This stores the address string the user typed plus its latitude and longitude so the
    backend doesn't have to re-geocode on every recompute.
    """
    __tablename__ ="workplaces"
    #Primary key for this row, UUID string which is autogenerated by _uuid() if not provided
    workplace_id:Mapped[str] =mapped_column(String,primary_key=True,default=_uuid)
    # Foreign key that links this workplace to its parent scenario.
    #`unique=True` enforces 1-to-1 at the DB level: only one workplace per scenario.
    #`nullable=False` because a workplace cannot exist without a scenario.
    scenario_id: Mapped[str]= mapped_column(
        ForeignKey("commute_scenarios.scenario_id"),
        unique=True,
        nullable=False,
    )
    #The raw address stirng the user inputted
    address: Mapped[str] = mapped_column(String, nullable=False)
    #lat from geocoding the address
    #Will be used as an anchor point for the commute calculations
    latitude: Mapped[float] = mapped_column(Float, nullable=False)
    #same thing for long
    longitude: Mapped[float] = mapped_column(Float, nullable=False)
    #This is the reverse side of ComutScenario, allows you to write "workplace.scenario"
    #in the code so we can go back to the owning scenario
    scenario: Mapped["CommuteScenario"] = relationship(back_populates="workplace")

#Now the Preference profile
#this is the commute and lifestyle preferences for a scenario
class PreferenceProfile(Base):

    """
    User preferences applied to scoring within a CommuteScenario.
    Updated by both manual filter changes and eventually with AI-driven
    refinement.
    """
    __tablename__ = "preference_profiles"
    #Primary key for this row.
    profile_id: Mapped[str] = mapped_column(String, primary_key=True, default=_uuid)
    #Foreign key to the parent scenario.
    #`unique=True` enforces 1-to-1: each scenario has exactly one preference profile.
    scenario_id: Mapped[str] = mapped_column(ForeignKey("commute_scenarios.scenario_id"),
        unique=True,
        nullable=False,
    )
    #Now for all of the preferences that the user can set
    #Hard cap on acceptable commute time. Default 45 matches a typical
    #max commute slider value. Used by US2 in Design doc to filter logic to dim zones over this limit.
    max_commute_minutes: Mapped[int] = mapped_column(Integer, nullable=False, default=45)
    #If True,routing will exclude highways. Toggled by the US-2 filter panel.
    avoid_highways: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    #maximum number of transit transfers the user is willing to make.
    #default 2 is typical for a reasonable transit commute.
    max_transfers: Mapped[int] = mapped_column(Integer, nullable=False, default=2)
    #user prefers transit over driving. Toggled by "transit-only" mode.
    prefers_transit: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    #User prefers driving over transit. Mutually exclusive with prefers_transit in practice.
    prefers_driving: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    #User wants a quieter neighborhood. Influences lifestyle scoring weight,
    #Primarily set by AI refinement in User story 3
    wants_quiet_area: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    #Reverse side of CommuteScenario.preference_profile. Lets you navigate back
    #with `profile.scenario`.
    scenario: Mapped["CommuteScenario"] = relationship(back_populates="preference_profile")


#now this is for the zone
#Each zone is a possible neighborhood
#It is referenced by Recommendation and HousingListing
#Only need to know about the listings
class Zone(Base):
    """
    This is a candidate neighborhood evaluated within a search.  The zones are geogrpahic and a zone
    can contain 0 or 1, or multiple housing listings
    """
    #the table name will just be zones
    __tablename__="zones"
    #the pimary key for this zone is the zone id
    zone_id: Mapped[str]=mapped_column(String, primary_key=True, default=_uuid)
    #this is the neighborhood name for us to be able to read it
    name: Mapped[str]=mapped_column(String, nullable=False)
    #this is now the GeoJSON polygon that provides the details about the zones boundry
    #we will use this later to draw on the map
    #I am going to make this optional for now we can represent 
    #a zone using purely the center point if no boundry is available
    #so it is optional and we should continue even without a value here(null)
    boundary_geo_json :Mapped[Optional[str]]=mapped_column(Text,nullable=True)
    #now for the latitude and longitude
    center_lat:Mapped[float]=mapped_column(Float,nullable=False)
    center_lng:Mapped[float]=mapped_column(Float, nullable=False)
    #now for the list of housing listings
    #Will future reference HousingListing
    listings: Mapped[list["HousingListing"]]=relationship(back_populates="zone",cascade="all, delete-orphan",)

#Now for the recommendation, it is one zones evaluation that is within a scenario
#so it is a score based on some context
class Recommendation(Base):
    """
    A single zones ranked evaluation within a CommuteScenario
    Produced by the RecommendationEngine. Each recommendation ties a zone
    to a scenario, whin then carries the computed rank and score, and owns exactly
    one CommuteAnalysis and one LifestyleAnalysis.
    """
    #postgres table name.
    __tablename__ = "recommendations"
    #primary key for this recommendation.
    recommendation_id: Mapped[str] = mapped_column(String, primary_key=True, default=_uuid)
    #foreign key to the parent scenario. Not unique a scenario has many
    #recommendations (one per candidate zone).
    scenario_id: Mapped[str] = mapped_column(
        ForeignKey("commute_scenarios.scenario_id"),
        nullable=False,
        index=True,
    )
    #foreign key to the zone this recommendation evaluates.
    zone_id: Mapped[str] = mapped_column(ForeignKey("zones.zone_id"),nullable=False,)
    #position in the ranked list. Set by the RecommendationEngine.
    rank: Mapped[int] = mapped_column(Integer, nullable=False)
    #overall computed score combining commute and lifestyle metrics.
    total_score: Mapped[float] = mapped_column(Float, nullable=False)
    #AI-generated plain-English explanation of why this zone ranks where it does.
    #nullable because it's only populated once the scenario reaches EXPLAINED state.
    explanation_summary: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    #reverse side of CommuteScenario.recommendations (added below). Navigate
    #back to the owning scenario with `recommendation.scenario`.
    scenario: Mapped["CommuteScenario"] = relationship(back_populates="recommendations")
    #the zone being evaluated. One-directional: we navigate recommendation -> zone,
    #but Zone doesn't track which recommendations reference it.
    zone: Mapped["Zone"] = relationship()
    #Each recommendation owns exactly one commute analysis and one lifestyle
    #analysis (1-to-1). uselist=False makes these single objects, not lists.
    commute_analysis: Mapped["CommuteAnalysis"] = relationship(
        back_populates="recommendation",
        uselist=False,
        cascade="all, delete-orphan",)
    lifestyle_analysis: Mapped["LifestyleAnalysis"] = relationship(
        back_populates="recommendation",
        uselist=False,
        cascade="all, delete-orphan",
    )
#now for the oommute analysis
class CommuteAnalysis(Base):
    """
    Computed commute metrics for one recommendation.Holds the routing/transit/traffic
    numbers that drive the commute portion of the score.
    """
    #postgres table name.
    __tablename__ = "commute_analyses"
    #primary key for this analysis row.
    analysis_id: Mapped[str] = mapped_column(String, primary_key=True, default=_uuid)
    #Foreign key to the parent recommendation. unique=True enforces 1-to-1.
    recommendation_id: Mapped[str] = mapped_column(
        ForeignKey("recommendations.recommendation_id"),
        unique=True,
        nullable=False,
    )
    #peak hour driving time from the zone to the workplace, in minutes.
    drive_time_peak_minutes:Mapped[float]= mapped_column(Float,nullable=False)
    #Peak-hour transit time from the zone to the workplace in minutes.
    transit_time_peak_minutes:Mapped[float]= mapped_column(Float,nullable=False)
    #walking time from the zone center to the nearest transit stop, in minutes.
    walking_minutes_to_stop:Mapped[float] =mapped_column(Float,nullable=False)
    #number of transit transfers required. Default 0 (direct route).
    transfer_count: Mapped[int] =mapped_column(Integer, nullable=False, default=0)
    # Traffic congestion level on a 0..1 scale (0 = clear, 1 = heavy). Default 0.
    congestion_level: Mapped[float] =mapped_column(Float,nullable=False,default=0.0)
    #reverse side of Recommendation.commute_analysis.
    recommendation: Mapped["Recommendation"] = relationship(back_populates="commute_analysis")
#Now for the lifestyle analysis 
class LifestyleAnalysis(Base):
    """
    Computed lifestyle scores for one recommendation.
    Holds the "quality of daily life" metrics that drive the lifestyle
    portion of the score. All scores default to 0.
    """
    __tablename__ = "lifestyle_analyses"
    #primary key for this analysis row.
    analysis_id: Mapped[str] = mapped_column(String, primary_key=True, default=_uuid)
    #foreign key to the parent recommendation. unique=True enforces 1-to-1.
    recommendation_id: Mapped[str] = mapped_column(
        ForeignKey("recommendations.recommendation_id"),
        unique=True,
        nullable=False,
    )
    #how walkable the neighborhood is, the higher the MORE walkable
    walkability_score: Mapped[float] = mapped_column(Float,nullable=False,default=0.0)
    #access to grocery stores.
    grocery_score:Mapped[float] = mapped_column(Float,nullable=False,default=0.0)
    #access to parks and green space.
    park_score:Mapped[float] = mapped_column(Float,nullable=False,default=0.0)
    #nightlife / entertainment availability.
    nightlife_score:Mapped[float] =mapped_column(Float,nullable=False,default=0.0)
    #How quiet the neighborhood is. Relevant to US-3
    #"I prefer quieter neighborhoods" refinement.
    quietness_score: Mapped[float]=mapped_column(Float, nullable=False, default=0.0)
    #reverse side of Recommendation.lifestyle_analysis.
    recommendation: Mapped["Recommendation"] =relationship(back_populates="lifestyle_analysis")
#Now for the housing listing 
#this is the actual unit within a zone
class HousingListing(Base):
    """
    A specific rental/housing unit within a zone.
    Fetched on demand from the housing provider when a user opens a zone
    detail panel (US-4), rather than pre-loaded with the initial results.
    """
    __tablename__ = "housing_listings"
    #primary key for this listing.
    listing_id: Mapped[str] = mapped_column(String, primary_key=True, default=_uuid)
    #Foreign key to the zone this listing belongs to. Not unique — a zone
    #has many listings.
    zone_id: Mapped[str] = mapped_column(
        ForeignKey("zones.zone_id"),
        nullable=False,
        index=True,
    )
    #street address of the unit.
    address: Mapped[str] = mapped_column(String, nullable=False)
    #the monthly rent in USD.
    rent: Mapped[float] = mapped_column(Float, nullable=False)
    #the Number of bedrooms. Default 1.
    bedrooms: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    #number of bathrooms (float to allow half-baths like 1.5). Default 1.0.
    bathrooms: Mapped[float] = mapped_column(Float, nullable=False, default=1.0)
    #direct URL to the external listing page (Zillow, etc.).
    url: Mapped[str] = mapped_column(String, nullable=False)
    #reverse side of Zone.listings. Navigate back with `listing.zone`.
    zone: Mapped["Zone"] = relationship(back_populates="listings")
