"""initial schema with auth fields

Revision ID: 7c444bf4394c
Revises: 
Create Date: 2026-05-31 20:32:07.770406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c444bf4394c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('zones',
    sa.Column('zone_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('boundary_geo_json', sa.Text(), nullable=True),
    sa.Column('center_lat', sa.Float(), nullable=False),
    sa.Column('center_lng', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('zone_id')
    )
    op.create_table('commute_scenarios',
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('search_radius_miles', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'ANALYZING', 'RANKED', 'EXPLAINED', 'FAILED', 'SAVED', name='scenario_status'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('scenario_id')
    )
    op.create_index(op.f('ix_commute_scenarios_user_id'), 'commute_scenarios', ['user_id'], unique=False)
    op.create_table('housing_listings',
    sa.Column('listing_id', sa.String(), nullable=False),
    sa.Column('zone_id', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('rent', sa.Float(), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Float(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.zone_id'], ),
    sa.PrimaryKeyConstraint('listing_id')
    )
    op.create_index(op.f('ix_housing_listings_zone_id'), 'housing_listings', ['zone_id'], unique=False)
    op.create_table('preference_profiles',
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('max_commute_minutes', sa.Integer(), nullable=False),
    sa.Column('avoid_highways', sa.Boolean(), nullable=False),
    sa.Column('max_transfers', sa.Integer(), nullable=False),
    sa.Column('prefers_transit', sa.Boolean(), nullable=False),
    sa.Column('prefers_driving', sa.Boolean(), nullable=False),
    sa.Column('wants_quiet_area', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['commute_scenarios.scenario_id'], ),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('scenario_id')
    )
    op.create_table('recommendations',
    sa.Column('recommendation_id', sa.String(), nullable=False),
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('zone_id', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('explanation_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['commute_scenarios.scenario_id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.zone_id'], ),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    op.create_index(op.f('ix_recommendations_scenario_id'), 'recommendations', ['scenario_id'], unique=False)
    op.create_table('workplaces',
    sa.Column('workplace_id', sa.String(), nullable=False),
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['commute_scenarios.scenario_id'], ),
    sa.PrimaryKeyConstraint('workplace_id'),
    sa.UniqueConstraint('scenario_id')
    )
    op.create_table('commute_analyses',
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('recommendation_id', sa.String(), nullable=False),
    sa.Column('drive_time_peak_minutes', sa.Float(), nullable=False),
    sa.Column('transit_time_peak_minutes', sa.Float(), nullable=False),
    sa.Column('walking_minutes_to_stop', sa.Float(), nullable=False),
    sa.Column('transfer_count', sa.Integer(), nullable=False),
    sa.Column('congestion_level', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.recommendation_id'], ),
    sa.PrimaryKeyConstraint('analysis_id'),
    sa.UniqueConstraint('recommendation_id')
    )
    op.create_table('lifestyle_analyses',
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('recommendation_id', sa.String(), nullable=False),
    sa.Column('walkability_score', sa.Float(), nullable=False),
    sa.Column('grocery_score', sa.Float(), nullable=False),
    sa.Column('park_score', sa.Float(), nullable=False),
    sa.Column('nightlife_score', sa.Float(), nullable=False),
    sa.Column('quietness_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.recommendation_id'], ),
    sa.PrimaryKeyConstraint('analysis_id'),
    sa.UniqueConstraint('recommendation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lifestyle_analyses')
    op.drop_table('commute_analyses')
    op.drop_table('workplaces')
    op.drop_index(op.f('ix_recommendations_scenario_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_table('preference_profiles')
    op.drop_index(op.f('ix_housing_listings_zone_id'), table_name='housing_listings')
    op.drop_table('housing_listings')
    op.drop_index(op.f('ix_commute_scenarios_user_id'), table_name='commute_scenarios')
    op.drop_table('commute_scenarios')
    op.drop_table('zones')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
